### PR TITLE
Api phpcs fixes

### PR DESCRIPTION
**Pull request by cooperaj**
## Purpose

Although the two projects (service-front, service-api) have had PHPCS installed for a while, it appears that neither have been run in a while. This PR includes the configuration and setup to update to PSR12 and then the changes corrected via `phpcbr`. There are still a few warnings to be fixed. 

In preparation for a more stringent set of commit hooks I've also installed and setup vimeo/psalm, a static code analyser that currently fails the project due to a lot of errors on our part. A future PR to fix will be needed before it is run as a part of the pipeline.

## Approach

Changes to composer.json to add newer version of phpcs. I've also added some new run aliases e.g. `composer run cs-fix | composer run unit-test` that run things in the docker containers

## Checklist

* [x] I have performed a self-review of my own code
* [x] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [x] I have added tests to prove my work
* [ ] The product team have tested these changes

### CODE REVIEW

**Comment by cooperaj** [comment]
When reviewing I would recommend you check it on a per commit basis and ignore https://github.com/ministryofjustice/opg-use-an-lpa/pull/219/commits/568816c7a1d81cd4c86959d36acbbe012349d389 and https://github.com/ministryofjustice/opg-use-an-lpa/pull/219/commits/6f49ffa4d508d3f1bedde7f2d05125ab647cee7a

**Comment by mattmachell** [comment]
Nice work! Not going to fully review, but would be interested to know why you went with Psalm over PHPStan.

Also, as a wider thing. Worth talking to @andrewpearce-digital about wiring the phpcs workflow into a pre-commit hook to avoid having to do a big PR like this again. 

And fainlly, probably a wider conversation with the team about configuring IDEs to do this automatically.

**Comment by cooperaj** [comment]
Automation all the way! But yes, it's been missing until now. @andrewpearce-digital has installed a package that will allow pre-commit hooks to run in a more developer friendly fashion but my brief look at the docs suggests it's lacking in the php department.

As to Psalm, I guess it's a personal preference thing. But I find the overall package to be a bit nicer and I enjoyed reading the [blog](https://medium.com/vimeo-engineering-blog/fixing-code-that-aint-broken-a99e05998c24) about it so...

**Comment by mattmachell** [comment]
> Automation all the way! But yes, it's been missing until now. @andrewpearce-digital has installed a package that will allow pre-commit hooks to run in a more developer friendly fashion but my brief look at the docs suggests it's lacking in the php department.

Good stuff. There's https://github.com/hootsuite/pre-commit-php which seems to be OK, but you can also wire up pre-commit to directly run anything CLI that you've got running in a docker container.

I'll take a look at the blog post, it's certainly a tool I'm not familiar enough with to make a call on! Worth coordinating with @ramchale and co, who I know have done a lot of PHPStan Neon work in Sirius recently so that we have some commonality in the projects.

**Pull request merged**
